# Generated by Django 5.2.17 on 2026-08-19 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(allow_unicode=True, max_length=200, unique=True)),
                ('short_description', models.TextField(blank=True)),
                ('hero_title', models.CharField(blank=True, max_length=255)),
                ('hero_subtitle', models.CharField(blank=True, max_length=255)),
                ('content', models.TextField(blank=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='services/pages/')),
                ('seo_title', models.CharField(blank=True, max_length=255)),
                ('seo_description', models.TextField(blank=True)),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='services/og/')),
                ('lead_service_type', models.CharField(choices=[('web_design', 'طراحی سایت'), ('seo', 'سئو سایت'), ('both', 'هر دو'), ('other', 'سایر')], default='other', max_length=20)),
                ('related_faq_page', models.CharField(choices=[('general', 'عمومی'), ('home', 'صفحه اصلی'), ('about', 'درباره ما'), ('web_design', 'طراحی سایت'), ('seo', 'سئو سایت'), ('portfolio', 'نمونه\u200cکارها'), ('contact', 'تماس')], default='general', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'صفحه خدمت',
                'verbose_name_plural': 'صفحات خدمات',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ServiceFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='services.servicepage')),
            ],
            options={
                'verbose_name': 'ویژگی خدمت',
                'verbose_name_plural': 'ویژگی\u200cهای خدمات',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ServicePricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('price_note', models.CharField(blank=True, max_length=255)),
                ('features', models.TextField(blank=True)),
                ('cta_text', models.CharField(default='درخواست مشاوره', max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricings', to='services.servicepage')),
            ],
            options={
                'verbose_name': 'پکیج خدمت',
                'verbose_name_plural': 'پکیج\u200cهای خدمات',
                'ordering': ['order', 'title'],
            },
        ),
    ]
