"""
CKEditor 5 upload integration tests.
Tests that the upload endpoint works and validates files properly.
"""
from django.test import TestCase, Client
from django.contrib.auth import get_user_model
from django.core.files.uploadedfile import SimpleUploadedFile

User = get_user_model()

# Valid PNG generated by Pillow (1x1 red pixel)
VALID_PNG = b'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x00\x01\x00\x00\x00\x01\x08\x06\x00\x00\x00\x1f\x15\xc4\x89\x00\x00\x00\rIDATx\x9cc\xf8\xcf\xc0\xf0\x1f\x00\x05\x00\x01\xff\x89\x99=\x1d\x00\x00\x00\x00IEND\xaeB`\x82'


class CKEditorUploadTests(TestCase):
    """Test CKEditor 5 file upload endpoint."""

    def setUp(self):
        self.client = Client()
        self.admin = User.objects.create_superuser('admin', 'admin@test.com', 'password')
        self.upload_url = '/ckeditor5/image_upload/'

    def test_upload_requires_auth(self):
        """Upload without auth returns 403 Forbidden."""
        image = SimpleUploadedFile('test.png', VALID_PNG, content_type='image/png')
        response = self.client.post(self.upload_url, {'upload': image})
        self.assertEqual(response.status_code, 403)

    def test_upload_requires_post(self):
        """GET to upload should return 405 Method Not Allowed."""
        self.client.force_login(self.admin)
        response = self.client.get(self.upload_url)
        self.assertEqual(response.status_code, 405)

    def test_upload_accepts_valid_image(self):
        """Upload should accept valid PNG images when authenticated."""
        self.client.force_login(self.admin)
        image = SimpleUploadedFile('test.png', VALID_PNG, content_type='image/png')
        response = self.client.post(self.upload_url, {'upload': image})
        self.assertIn(response.status_code, [200, 201])

    def test_upload_rejects_non_image(self):
        """Upload of non-image file should fail."""
        self.client.force_login(self.admin)
        text_file = SimpleUploadedFile('test.txt', b'hello', content_type='text/plain')
        response = self.client.post(self.upload_url, {'upload': text_file})
        self.assertNotEqual(response.status_code, 200)

    def test_upload_rejects_executable(self):
        """Upload of executable file should fail."""
        self.client.force_login(self.admin)
        exe_file = SimpleUploadedFile('malware.exe', b'MZ\x90\x00', content_type='application/x-executable')
        response = self.client.post(self.upload_url, {'upload': exe_file})
        self.assertNotEqual(response.status_code, 200)
