# Generated by Django 5.2.17 on 2026-08-19 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='درباره تبریز سایت', max_length=200)),
                ('intro', models.TextField(blank=True)),
                ('story_title', models.CharField(blank=True, max_length=200)),
                ('story_content', models.TextField(blank=True)),
                ('mission_title', models.CharField(blank=True, max_length=200)),
                ('mission_content', models.TextField(blank=True)),
                ('vision_title', models.CharField(blank=True, max_length=200)),
                ('vision_content', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='pages/about/')),
                ('seo_title', models.CharField(blank=True, max_length=255)),
                ('seo_description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'درباره ما',
                'verbose_name_plural': 'درباره ما',
            },
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='طراحی سایت و سئو در تبریز', max_length=255)),
                ('hero_subtitle', models.TextField(blank=True)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='pages/home/')),
                ('primary_cta_text', models.CharField(default='درخواست مشاوره رایگان', max_length=100)),
                ('primary_cta_url', models.CharField(default='/contact/', max_length=255)),
                ('secondary_cta_text', models.CharField(blank=True, max_length=100)),
                ('secondary_cta_url', models.CharField(blank=True, max_length=255)),
                ('services_heading', models.CharField(default='خدمات تبریز سایت', max_length=200)),
                ('services_subheading', models.TextField(blank=True)),
                ('portfolio_heading', models.CharField(default='نمونه\u200cکارهای منتخب', max_length=200)),
                ('portfolio_subheading', models.TextField(blank=True)),
                ('testimonials_heading', models.CharField(default='نظرات مشتریان', max_length=200)),
                ('faq_heading', models.CharField(default='سوالات متداول', max_length=200)),
                ('blog_heading', models.CharField(default='آخرین مقالات', max_length=200)),
                ('cta_title', models.CharField(default='برای شروع پروژه آماده\u200cای؟', max_length=255)),
                ('cta_subtitle', models.TextField(blank=True)),
                ('cta_button_text', models.CharField(default='درخواست مشاوره', max_length=100)),
                ('cta_button_url', models.CharField(default='/contact/', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'صفحه اصلی',
                'verbose_name_plural': 'صفحه اصلی',
            },
        ),
        migrations.CreateModel(
            name='LegalPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(allow_unicode=True, max_length=200, unique=True)),
                ('content', models.TextField(blank=True)),
                ('seo_title', models.CharField(blank=True, max_length=255)),
                ('seo_description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'صفحه قانونی',
                'verbose_name_plural': 'صفحات قانونی',
                'ordering': ['order', 'title'],
            },
        ),
    ]
